postgres:
  image: postgres:9.5.3
  volumes:
    - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    - ~/volumes/ckan/postgres:/var/lib/postgresql/data
  environment:
    - PGDATA=/var/lib/postgresql/data
    - CKAN_USER=ckan_default
    - CKAN_PASSWORD=ckan_pass
    - CKAN_DB=ckan_default
    - DATASTORE_USER=datastore_default
    - DATASTORE_PASSWORD=datastore_pass
    - DATASTORE_DB=datastore_default

solr:
  image: solr:6.0.0
  # ports:
  #   - "8983:8983"
  volumes:
    - ./solr/precreate-core.sh:/docker-entrypoint-initdb.d/precreate-core.sh
    - ~/volumes/ckan/solr:/opt/solr/server/solr/ckan-core
  user: root
  environment:
    - SOLR_CKAN_CORE=ckan-core

# datapusher:
#   build: _service-provider/_datapusher
#   hostname: datapusher
#   domainname: localdomain
#   ports:
#     - "8800:8800"

ckan:
  build: .
  ports:
    - "5000:5000"
  links:
    - postgres:postgres
    - solr:solr
    # - datapusher:datapusher
  volumes:
    - ./config/custom-options.ini:/etc/ckan/default/custom-options.ini
    - ~/volumes/ckan/data:/var/lib/ckan/default
  environment:
    - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:ckan_pass@postgres/ckan_default
    - CKAN_DATASTORE_WRITE_URL=postgresql://ckan_default:ckan_pass@postgres/datastore_default
    - CKAN_DATASTORE_READ_URL=postgresql://datastore_default:datastore_pass@postgres/datastore_default
    - CKAN_SOLR_URL=http://solr:8983/solr/ckan-core
    - CKAN_SITE_ID=default
    - CKAN_SITE_URL=http://10.32.66.36:5000
    - CKAN_STORAGE_PATH=/var/lib/ckan/default
    # - CKAN_DATAPUSHER_URL=
    # - CKAN_SMTP_SERVER=
    # - CKAN_SMTP_STARTTLS=
    # - CKAN_SMTP_USER=
    # - CKAN_SMTP_PASSWORD=
    # - CKAN_SMTP_MAIL_FROM=
